export enum FoulEnum {
  TOUCHING_BALLS = 'TOUCHING_BALLS',
  PLACEMENT = 'PLACEMENT',
  DOUBLE_HIT = 'DOUBLE_HIT',
  PUSH_SHOT = 'PUSH_SHOT',
  ILLEGAL_JUMPING = 'ILLEGAL_JUMPING',
  OFF_TABLE = 'OFF_TABLE',
}
